FROM python:3.11-slim
RUN apt-get update && apt-get install -y --no-install-recommends \
    tesseract-ocr tesseract-ocr-eng libtesseract-dev libgl1 libglib2.0-0 libsm6 \
    libxext6 libxrender1 libgomp1 poppler-utils && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY requirements.txt .
RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt
COPY src/streamlit ./src/streamlit
COPY models ./models
EXPOSE 8501
CMD ["streamlit", "run", "src/streamlit/streamlit_application.py", "--server.port=8501"]
